#!/usr/bin/env bash

cat ~/.tplsmacros > ~/rpmbuild/SPECS/tpls-$1.spec
cat ~/rpmbuild/TEMPLATES/tpls-$1.spec >> ~/rpmbuild/SPECS/tpls-$1.spec
spectool -g -R ~/rpmbuild/SPECS/tpls-$1.spec
rpmbuild -ba ~/rpmbuild/SPECS/tpls-$1.spec

